export const categories = [
  { title: "Fullstack", id: 1 },
  { title: "Frontend", id: 2 },
  { title: "Backend", id: 3 },
];
export const techStacks = [
  { id: 1, title: "Python" },
  { id: 2, title: "Django" },
  { id: 3, title: "Javascript" },
  { id: 4, title: "React" },
];
export const projects = [
  {
    id: 1,
    category: [3, 4],
    title: "React frontend",
    description: "A practice frontend",
    image: "https://source.unsplash.com/m_HRfLhgABo",
    demo: "#",
    live: null,
    blogPost: null,
  },
  {
    id: 2,
    category: [1, 2, 3],
    title: "Enrollment app",
    description: "An app for course enrollment",
    image: "https://source.unsplash.com/glRqyWJgUeY",
    demo: "https://ositainstitute.netlify.app",
    github: "https://ositainstitute.com",
    live: "https://ositainstitute.com",
    blogPost: "http://localhost:3000/blog",
  },
  {
    id: 1,
    category: [3],
    title: "React frontend React frontend React frontend React frontend ",
    description:
      "A practice frontend A practice frontend A practice frontendvv A practice frontend A practice frontend A practice frontend A practice frontend A practice frontend v A practice frontend",
    image: "https://source.unsplash.com/pMW4jzELQCw",
    github: "#",
    demo: "#",
    live: "https://ositainstitute.netlify.app",
    blogPost: "#",
  },
  {
    id: 2,
    category: [1, 2, 3],
    title: "Enrollment app",
    description: "An app for course enrollment",
    image: "https://source.unsplash.com/obV_LM0KjxY",
    github: "#",
    demo: "https://ositainstitute.netlify.app",
    live: "#",
    blogPost: "#",
  },
  {
    id: 1,
    category: [3],
    title: "React frontend",
    description: "A practice frontend",
    image: "https://source.unsplash.com/h28p96ICizo",
    github: "#",
    demo: "#",
    live: "#",
    blogPost: "#",
  },
  {
    id: 2,
    category: [1, 2, 3],
    title: "Enrollment app",
    description: "An app for course enrollment",
    image: "https://source.unsplash.com/aaHwnxgBmHs",
    github: "#",
    demo: "#",
    live: "#",
    blogPost: "#",
  },
  {
    id: 1,
    category: [3],
    title: "React frontend",
    description: "A practice frontend",
    image: "https://source.unsplash.com/XkjM6VYkJhE",
    github: "#",
    demo: "#",
    live: "#",
    blogPost: "#",
  },
  {
    id: 2,
    category: [1, 2, 3],
    title: "Enrollment app",
    description: "An app for course enrollment",
    image: "https://source.unsplash.com/PiaYklUnxmc",
    github: "#",
    demo: "#",
    live: "#",
    blogPost: "#",
  },
  {
    id: 3,
    category: [3],
    title: "React frontend",
    description: "A practice frontend",
    image: "https://source.unsplash.com/sbVu5zitZt0",
    github: "#",
    demo: "#",
    live: "#",
    blogPost: "#",
  },
  {
    id: 4,
    category: [1, 2, 3],
    title: "Enrollment app",
    description: "An app for course enrollment",
    image: "https://source.unsplash.com/UEVeZOUYHGw",
    github: "#",
    demo: "#",
    live: "#",
    blogPost: "#",
  },
  {
    id: 5,
    category: [3],
    title: "React frontend",
    description: "A practice frontend",
    image: "https://source.unsplash.com/2EJCSULRwC8",
    github: "#",
    demo: "#",
    live: "#",
    blogPost: "#",
  },
  {
    id: 6,
    category: [1, 2, 3],
    title: "Enrollment app",
    description: "An app for course enrollment",
    image: "https://source.unsplash.com/y2WF_FEGVNw",
    github: "#",
    demo: "#",
    live: "#",
    blogPost: "#",
  },
  {
    id: 7,
    category: [3],
    title: "React frontend",
    description: "A practice frontend",
    image: "https://source.unsplash.com/YKW0JjP7rlU",
    github: "#",
    demo: "#",
    live: "#",
    blogPost: "#",
  },
  {
    id: 8,
    category: [1, 2, 3],
    title: "Enrollment app",
    description: "An app for course enrollment",
    image: "https://source.unsplash.com/B2OV_nwcbxM",
    github: "#",
    demo: "#",
    live: "#",
    blogPost: "#",
  },
  {
    id: 9,
    category: [3],
    title: "React frontend",
    description: "A practice frontend",
    image: "https://source.unsplash.com/MxVkWPiJALs",
    github: "#",
    demo: "#",
    live: "#",
    blogPost: "#",
  },
  {
    id: 10,
    category: [1, 2, 3],
    title: "Enrollment app",
    description: "An app for course enrollment",
    image: "https://source.unsplash.com/Q1p7bh3SHj8",
    github: "#",
    demo: "#",
    live: "#",
    blogPost: "#",
  },
];
